import { Product, Category, BlogPost } from './types';

// DEMO PRODUCT DATA
// Replace these with your real affiliate products
export const products: Product[] = [
  {
    id: 'p1',
    name: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones',
    slug: 'sony-wh-1000xm5-wireless-headphones',
    category: 'Electronics',
    brand: 'Sony',
    image: 'https://picsum.photos/seed/sony-xm5/800/800',
    description: 'Industry leading noise cancellation with two processors control 8 microphones for unprecedented noise cancellation. With Auto NC Optimizer, noise canceling is automatically optimized based on your wearing conditions and environment.',
    price: 348.00,
    originalPrice: 399.99,
    discount: 13,
    rating: 4.8,
    reviewCount: 12450,
    affiliateUrl: 'https://affiliate-link.example.com/product/sony-xm5',
    featured: true,
    trending: true,
    bestseller: true,
    highlights: ['Industry leading noise cancellation', 'Up to 30-hour battery life', 'Ultra-comfortable, lightweight design'],
    pros: ['Excellent active noise cancellation', 'Superb sound quality', 'Very comfortable for long sessions'],
    cons: ['Not water resistant', 'Cannot fold up compactly'],
    specs: { 'Battery Life': '30 Hours', 'Weight': '250g', 'Bluetooth': 'Version 5.2' }
  },
  {
    id: 'p2',
    name: 'Apple MacBook Air M3 (2024) - 13-inch',
    slug: 'apple-macbook-air-m3-2024',
    category: 'Laptops',
    brand: 'Apple',
    image: 'https://picsum.photos/seed/macbook-m3/800/800',
    description: 'The M3 chip brings even greater capabilities to the superportable 13-inch MacBook Air. With up to 18 hours of battery life, you can take it anywhere and blaze through work and play.',
    price: 999.00,
    originalPrice: 1099.00,
    discount: 9,
    rating: 4.9,
    reviewCount: 3820,
    affiliateUrl: 'https://affiliate-link.example.com/product/macbook-m3',
    featured: true,
    trending: true,
    bestseller: true,
    highlights: ['Apple M3 chip', '13.6-inch Liquid Retina display', 'Up to 18 hours battery life'],
    pros: ['Incredible performance for the size', 'Silent fanless design', 'Excellent keyboard and trackpad'],
    cons: ['Base model has limited storage', 'Only two USB-C ports'],
    specs: { 'Processor': 'Apple M3', 'RAM': '8GB', 'Storage': '256GB SSD', 'Display': '13.6" Liquid Retina' }
  },
  {
    id: 'p3',
    name: 'Ninja AF101 Air Fryer that Crisps, Roasts, Reheats',
    slug: 'ninja-af101-air-fryer',
    category: 'Home & Kitchen',
    brand: 'Ninja',
    image: 'https://picsum.photos/seed/ninja-fryer/800/800',
    description: 'Now enjoy guilt-free food. Air fry with up to 75 percent less fat than traditional frying methods. Maximize your counter space with this compact, powerful 4 quart air fryer.',
    price: 89.99,
    originalPrice: 129.99,
    discount: 31,
    rating: 4.7,
    reviewCount: 45000,
    affiliateUrl: 'https://affiliate-link.example.com/product/ninja-air-fryer',
    featured: true,
    trending: false,
    bestseller: true,
    highlights: ['4 Quart Capacity', '4 Programmable Cooking Functions', 'Dishwasher Safe Parts'],
    pros: ['Very easy to clean', 'Cooks fast and evenly', 'Compact footprint'],
    cons: ['May be too small for large families', 'Can be loud during operation'],
    specs: { 'Capacity': '4 Quarts', 'Wattage': '1500W', 'Weight': '10.58 lbs' }
  },
  {
    id: 'p4',
    name: 'Samsung 49" Odyssey G9 Gaming Monitor',
    slug: 'samsung-odyssey-g9-monitor',
    category: 'Gaming',
    brand: 'Samsung',
    image: 'https://picsum.photos/seed/samsung-g9/800/800',
    description: 'Samsung’s largest 1000R gaming monitor. Get your head in the game with the 49 inch Odyssey G9, which matches the curve of the human eye, for maximum immersion and minimal eye strain.',
    price: 999.99,
    originalPrice: 1399.99,
    discount: 29,
    rating: 4.5,
    reviewCount: 2100,
    affiliateUrl: 'https://affiliate-link.example.com/product/samsung-g9',
    featured: true,
    trending: true,
    bestseller: false,
    highlights: ['49-inch curved screen', '240Hz Refresh Rate', '1ms Response Time', 'Dual QHD Resolution'],
    pros: ['Incredibly immersive', 'Ultra-fast refresh rate', 'Great HDR performance'],
    cons: ['Takes up a lot of desk space', 'Very heavy', 'Expensive'],
    specs: { 'Screen Size': '49 Inches', 'Resolution': '5120 x 1440', 'Refresh Rate': '240Hz' }
  },
  {
    id: 'p5',
    name: 'Fitbit Charge 6 Fitness Tracker',
    slug: 'fitbit-charge-6',
    category: 'Fitness',
    brand: 'Fitbit',
    image: 'https://picsum.photos/seed/fitbit-c6/800/800',
    description: 'Give your routine a boost with Charge 6, the only fitness tracker with Google built in. Charge 6 has your favorite Google essentials, like Maps and Wallet, right on your wrist.',
    price: 139.95,
    originalPrice: 159.95,
    discount: 13,
    rating: 4.3,
    reviewCount: 5600,
    affiliateUrl: 'https://affiliate-link.example.com/product/fitbit-charge-6',
    featured: false,
    trending: true,
    bestseller: true,
    highlights: ['Google apps built-in', 'Heart rate tracking', 'Built-in GPS'],
    pros: ['Accurate fitness tracking', 'Comfortable to wear', 'Good battery life'],
    cons: ['Small screen', 'Requires premium subscription for advanced data'],
    specs: { 'Battery Life': 'Up to 7 days', 'Water Resistance': '50 meters', 'GPS': 'Built-in' }
  },
  {
    id: 'p6',
    name: 'YETI Rambler 20 oz Tumbler',
    slug: 'yeti-rambler-20oz',
    category: 'Travel',
    brand: 'YETI',
    image: 'https://picsum.photos/seed/yeti-20oz/800/800',
    description: 'Any tumbler that\'s coming along for the ride needs to be tough enough to keep up. Our Rambler 20 oz. is made from durable stainless steel with double-wall vacuum insulation.',
    price: 35.00,
    originalPrice: 35.00,
    discount: 0,
    rating: 4.8,
    reviewCount: 89000,
    affiliateUrl: 'https://affiliate-link.example.com/product/yeti-rambler',
    featured: false,
    trending: true,
    bestseller: true,
    highlights: ['Double-Wall Vacuum Insulation', 'MagSlider Lid', 'Dishwasher Safe'],
    pros: ['Keeps drinks hot/cold for hours', 'Indestructible build', 'Fits in most cup holders'],
    cons: ['Lid is not 100% leakproof', 'Premium price for a cup'],
    specs: { 'Capacity': '20 oz', 'Material': 'Stainless Steel' }
  },
  {
    id: 'p7',
    name: 'Logitech MX Master 3S Wireless Mouse',
    slug: 'logitech-mx-master-3s',
    category: 'Office Products',
    brand: 'Logitech',
    image: 'https://picsum.photos/seed/mx-master/800/800',
    description: 'The iconic mouse, remastered. Feel every moment of your workflow with even more precision, tactility, and performance, thanks to Quiet Clicks and an 8,000 DPI track-on-glass sensor.',
    price: 99.99,
    originalPrice: 99.99,
    discount: 0,
    rating: 4.7,
    reviewCount: 14500,
    affiliateUrl: 'https://affiliate-link.example.com/product/mx-master-3s',
    featured: false,
    trending: true,
    bestseller: true,
    highlights: ['Quiet Clicks', '8K DPI tracking', 'MagSpeed scroll wheel'],
    pros: ['Ergonomic comfort', 'Excellent scrolling experience', 'Multi-device pairing'],
    cons: ['Right-handed only design', 'Bulky for travel'],
    specs: { 'Sensor': '8000 DPI', 'Buttons': '7', 'Connectivity': 'Bluetooth / Logi Bolt' }
  },
  {
    id: 'p8',
    name: 'Anker 735 Charger (GaNPrime 65W)',
    slug: 'anker-735-charger',
    category: 'Accessories',
    brand: 'Anker',
    image: 'https://picsum.photos/seed/anker-charger/800/800',
    description: 'Power 3 Devices at Once: With 2 USB-C ports and one USB-A port, you can charge your phone, notebook, and earbuds all at once from a single charger.',
    price: 39.99,
    originalPrice: 59.99,
    discount: 33,
    rating: 4.8,
    reviewCount: 8200,
    affiliateUrl: 'https://affiliate-link.example.com/product/anker-735',
    featured: false,
    trending: false,
    bestseller: true,
    highlights: ['65W Max Output', 'GaNPrime Technology', '3 Ports (2C1A)'],
    pros: ['Compact size', 'Powerful enough for laptops', 'Reliable Anker quality'],
    cons: ['Can get warm during heavy use', 'Power splits when using multiple ports'],
    specs: { 'Output': '65W Max', 'Ports': '2x USB-C, 1x USB-A', 'Technology': 'GaN' }
  }
];

export const categories: Category[] = [
  { name: 'Electronics', slug: 'electronics', icon: 'Cpu' },
  { name: 'Smartphones', slug: 'smartphones', icon: 'Smartphone' },
  { name: 'Laptops', slug: 'laptops', icon: 'Laptop' },
  { name: 'Fashion', slug: 'fashion', icon: 'Shirt' },
  { name: 'Home & Kitchen', slug: 'home-kitchen', icon: 'Home' },
  { name: 'Beauty', slug: 'beauty', icon: 'Sparkles' },
  { name: 'Fitness', slug: 'fitness', icon: 'Dumbbell' },
  { name: 'Gaming', slug: 'gaming', icon: 'Gamepad2' },
  { name: 'Accessories', slug: 'accessories', icon: 'Headphones' },
  { name: 'Travel', slug: 'travel', icon: 'Plane' },
  { name: 'Office Products', slug: 'office', icon: 'Briefcase' },
  { name: 'Trending Products', slug: 'trending', icon: 'TrendingUp' }
];

export const blogPosts: BlogPost[] = [
  {
    id: 'b1',
    title: 'Best Budget Smartphones in 2026',
    slug: 'best-budget-smartphones',
    excerpt: 'You don\'t need to spend $1000 to get a great phone anymore. Here are the top budget phones that deliver flagship-level features.',
    content: 'Full article content would go here...',
    image: 'https://picsum.photos/seed/blog-phones/800/500',
    date: '2026-09-01',
    author: 'Vibes Editorial'
  },
  {
    id: 'b2',
    title: 'Best Wireless Headphones for Work and Travel',
    slug: 'best-wireless-headphones',
    excerpt: 'Block out the noise and focus on what matters. We tested the top wireless noise-canceling headphones to find the absolute best.',
    content: 'Full article content would go here...',
    image: 'https://picsum.photos/seed/blog-headphones/800/500',
    date: '2026-09-05',
    author: 'Vibes Editorial'
  },
  {
    id: 'b3',
    title: 'How to Find the Best Online Deals',
    slug: 'how-to-find-deals',
    excerpt: 'Stop overpaying. Learn the insider secrets to finding the absolute lowest prices on your favorite online stores.',
    content: 'Full article content would go here...',
    image: 'https://picsum.photos/seed/blog-deals/800/500',
    date: '2026-09-08',
    author: 'Vibes Editorial'
  }
];
